# Generated by Django 5.2.1 on 2025-05-24 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Категория рецепта',
                'verbose_name_plural': 'Категории рецептов',
                'unique_together': {('recipe', 'category')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeCategory', to='recipes.category', verbose_name='Категории'),
        ),
    ]
